name: CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
         
    - name: Publish (Selfcontained)
      run: dotnet publish -c Release -r win-x64 --self-contained -o publish-selfcontained
      
    - name: Publish (Singlefile)
      run: dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true --self-contained false -o publish-singlefile
            
    - name: GitHub Publish - Archive (Selfcontained)
      run: powershell Compress-Archive -Path publish-selfcontained\* -DestinationPath DalleMiniViewer-SelfContained.zip
      
    - name: GitHub Publish - Archive (Singlefile)
      run: powershell Compress-Archive -Path publish-singlefile\* -DestinationPath DalleMiniViewer-SingleFile.zip
      
    - name: GitHub Publish - Release
      uses: softprops/action-gh-release@v1      
      with:
        tag_name: ${{ github.workflow }}
        name: Release v${{ github.run_number }}
        draft: false
        prerelease: true
        files:
          DalleMiniViewer*.zip
